{ Hinweise zum Compilieren des Programms                                     }
{ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                     }
{ -keine Probleme mit Borland/Turbo Pascal 7.0                               }
{ -fÅr Turbo Pascal 6.0: -"BREAK"-/"CONTINUE"-Anweisungen durch "GOTO LABEL" }
{                         ersetzen                                           }
{                        -evt. diversen Funktionsaufrufen Variablen zuordnen }
{ -fÅr Turbo Pascal 5.0 und darunter: Probieren!                             }
{                                                                            }
USES Menu;

BEGIN
  RunMenu;
END.